# Generated by Django 5.2.1 on 2025-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_alter_service_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
