# Generated by Django 5.2.1 on 2025-05-22 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('appliance', 'Appliance Repair'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
